### ISSUE TITLE
rasterio installation fails on Windows (GDAL dependency)

### ISSUE THREAD

**Issue by sbaber1** [nasaharvest/cropharvest#71]
`pip install cropharvest ` in Windows-based (Windows 10) miniconda prompt fails based on GDAL dependency. 

Below is the error message from terminal:

`Collecting rasterio>=1.2.6
  Using cached rasterio-1.2.10.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`
[Rasterio docs](https://rasterio.readthedocs.io/en/latest/installation.html) calls for providing file location of GDAL binary. 

Resorting to working with Windows Linux Subsystem, but not all potential users might have this option?

**Comment by gabrieltseng** [comment]
This is related: https://github.com/nasaharvest/cropharvest/issues/52

cc: @ivanzvonkov

**Comment by sbaber1** [comment]
(I'll close this issue and defer to #52 . Thank you!)
