### ISSUE TITLE
test file error

### ISSUE THREAD

**Issue by wllih** [nasaharvest/cropharvest#81]
Hello, I am also participating in this competition for the first time this year, so I would like to ask about the data set of this competition. The data set of the competition is downloaded in a total of 4 parts (labels.geojson/eo_data/features/test_features), and in github The engineer file is provided to generate features and test_features through the *.tif files in eo_data, but I can only generate features, and only togo_eval.h5 files can be generated in test_features, and the other four files cannot be generated? Is there something missing from data generation?

![image](https://user-images.githubusercontent.com/18713813/162379149-d6a0b343-bf03-4e4b-86ae-248baba4020e.png)

**Comment by wllih** [comment]
In addition, I would like to ask, is the test data set submitted by the competition the monitoring results of the 5 files in test_features?

**Comment by gabrieltseng** [comment]
Hi! 

If you have questions specifically relating to the competition: the complete instructions for participating in the competition can be found on the [challenge website](https://www.agriculture-vision.com/agriculture-vision-2022/prize-challenge-2022/cropharvest-challenge-2022) and the [submission website](https://codalab.lisn.upsaclay.fr/competitions/2658?secret_key=605265b8-db3c-4b34-a568-cd4439518236#learn_the_details-overview). Please direct any questions about the logistics of participating, submitting, etc. to Najmul Hassan <[Najmulh@uoregon.edu](mailto:Najmulh@uoregon.edu)> and Kai Wang <[Kwang6@uoregon.edu](mailto:Kwang6@uoregon.edu)>.

If you are trying to run code in this repository and are running into an error, I can try and help! What exactly is the script you are running? From the error you are getting, it does seem like missing data is the issue.
